### ISSUE TITLE
Undefined index: token_type

### ISSUE THREAD

**Issue by stevenscg** [Sainsburys/guzzle-oauth2-plugin#5]
FYI, this issue should only apply when a server response is non-conforming (which is what I'm dealing with, unfortunately)...

When using the middleware with an existing but expired access token (set via `setAccessToken()`) against a non-conforming server, the following PHP Notice is triggered:

```
Undefined index: token_type [ROOT/vendor/sainsburys/guzzle-oauth2-plugin/src/GrantType/GrantTypeBase.php, line 136]
```

The refresh token response from this particular auth server is of the form:
```JSON
{
  "access_token": "adf9ad9d9d9f9f9",
  "expires_at": 1466008449,
  "user_id": 12345
}
```

Would it be possible to protect against this (with a `null`) or provide the `token_type` via config or constructor?

**Comment by dm** [comment]
Hi @stevenscg 

I am unsure if we should try to cover edge cases such as that (and probably create more issues down the line) where a server is non-conforming.
You're aware that token_type is REQUIRED as per RFC6749 which is what we're covering and I'd prefer to reach out to the service being consumed and attempt to get this corrected.

If not, the way you're suggesting is going through creating accessors to avoid/quiet down PHP Notices when accessing unset array keys; which to me breaks what should be a valid notice on conforming services.

Since we're creating servers implementing OAuth 2.0; I'd prefer that a consumer can catch these errors, and seek them being corrected with a proper implementation.

Thanks for reaching out :)
